---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-kubelan
  namespace: kube-system
rules:
  - apiGroups: ['discovery.k8s.io']
    resources: ['endpointslices']
    verbs: ['watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-kubelan
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: traefik-kubelan
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: kube-system
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    fluxcd.io/automated: 'true'
    repository.fluxcd.io/traefik: image.name
    tag.fluxcd.io/traefik: image.tag
    filter.fluxcd.io/traefik: glob:2.3.*
    fluxcd.io/ignore: 'true'
spec:
  releaseName: traefik
  helmVersion: v3
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.4.3
  values:
    image:
      name: ghcr.io/netsoc/traefik
      tag: latest
    logs:
      general:
        level: DEBUG
    ingressRoute:
      dashboard:
        enabled: false
    additionalArguments:
    - '--accesslog=true'
    - '--api.dashboard=true'
    deployment:
      replicas: 1
      additionalContainers:
        - name: kubelan
          image: 'ghcr.io/devplayer0/kubelan:0.2.2'
          env:
            - name: KL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: IFACE_IP
              value: '172.24.254.3/16'

            - name: KL_LOG_LEVEL
              value: DEBUG
            - name: KL_SERVICES
              value: 'traefik,webspace-ng/dnsmasq,webspace-ng/lxd8s,webspace-ng/webspaced'
            - name: KL_VXLAN_INTERFACE
              value: lxd-overlay
            - name: KL_VXLAN_VNI
              value: '7331'
            - name: KL_HOOKS_UP
              value: 'sh,-c,ip addr add $IFACE_IP dev $IFACE'
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
          securityContext:
            capabilities:
              add: [NET_ADMIN]
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  routes:
  - match: Host(`traefik.k8s`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
    - name: auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: kube-system
spec:
  basicAuth:
    secret: traefik-dashboard-users
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-redirect
  namespace: kube-system
spec:
  redirectRegex:
    regex: '^http://traefik.k8s/(.*)'
    replacement: 'http://traefik.k8s/dashboard/${1}'
