---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    fluxcd.io/automated: 'true'
    repository.fluxcd.io/traefik: image.name
    tag.fluxcd.io/traefik: image.tag
    filter.fluxcd.io/traefik: glob:2.3.*
spec:
  releaseName: traefik
  helmVersion: v3
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.4.3
  values:
    image:
      name: ghcr.io/netsoc/traefik
      tag: 2.3.0-9bd3fc3f
    deployment:
      replicas: 1
    logs:
      general:
        level: DEBUG
    ingressRoute:
      dashboard:
        enabled: false
    additionalArguments:
    - '--accesslog=true'
    - '--api.dashboard=true'
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  routes:
  - match: Host(`traefik.k8s`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
    - name: auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: kube-system
spec:
  basicAuth:
    secret: traefik-dashboard-users
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-redirect
  namespace: kube-system
spec:
  redirectRegex:
    regex: '^http://traefik.k8s/(.*)'
    replacement: 'http://traefik.k8s/dashboard/${1}'
